### ISSUE TITLE
Problems under some UI

### ISSUE THREAD

**Issue by as0770** [AlexKent3141/OnePunchGo#1]
Some UI don't send time_left after time_settings, OPG can't handle this. I fixed it with a hack in CommsHandler.cpp:

```
`        else if (command == "time_settings")
        {
            int mainTime = stoi(tokens[i]);
            int byoyomiTime = stoi(tokens[i+1]);
            int byoyomiStones = stoi(tokens[i+2]);
            _timeInfos[0] = TimeInfo(mainTime, byoyomiTime, byoyomiStones);
            _timeInfos[1] = TimeInfo(mainTime, byoyomiTime, byoyomiStones);

            int timeLeft = mainTime;
            int stonesLeft = 0;
            _timeInfos[0].TimeLeft(timeLeft, stonesLeft);
	    _timeInfos[1].TimeLeft(timeLeft, stonesLeft);

            SuccessResponse(id, "");`
```

**Comment by AlexKent3141** [comment]
Makes sense - I will put together a fix which defaults the "time left" sensibly.

Could you point me towards the UI that you used to find this issue? It seems that GoGui always sends this info, but maybe it depends on the time settings that you choose...

**Comment by as0770** [comment]
I used twogtp. Try:

`gogui-twogtp -auto -white "OPG" -black "gnugo --mode gtp --level 10 --resign-allowed" -games 2 -size 19 -time 60 -verbose -sgffile w-opg-b-gnugo`

I also tried Sabaki.

**Comment by AlexKent3141** [comment]
I've opened a PR containing this fix: https://github.com/AlexKent3141/OnePunchGo/pull/2

Essentially what you did but in the TimeInfo class.

BTW: it's still not ideal because now OPG always thinks it has the full game time remaining unless it receives a "time_left" message! I guess the only way to address this would be to keep track of time remaining internally, though this doesn't seem like something the engine should need to do...

**Comment by as0770** [comment]
Yes, twogtp doesn't send the time_left command at all. I don't know if it is required by the gtp protocol. I guess no because I have not observed problems like that with other engines so far. Anyway thanks for the fix!

**Comment by AlexKent3141** [comment]
Merged into master.
